download_url: https://galaxy.ansible.com/download/netapp_eseries-santricity-1.4.0.tar.gz
format_version: 1.0.0
name: santricity
namespace: netapp_eseries
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.4.0
version_url: https://galaxy.ansible.com/api/v2/collections/netapp_eseries/santricity/versions/1.4.0/
