download_url: https://galaxy.ansible.com/download/dellemc-os10-1.1.1.tar.gz
format_version: 1.0.0
name: os10
namespace: dellemc
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.1.1
version_url: https://galaxy.ansible.com/api/v2/collections/dellemc/os10/versions/1.1.1/
