download_url: https://galaxy.ansible.com/download/vmware-vmware_rest-2.3.1.tar.gz
format_version: 1.0.0
name: vmware_rest
namespace: vmware
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.3.1
version_url: https://galaxy.ansible.com/api/v2/collections/vmware/vmware_rest/versions/2.3.1/
