download_url: https://galaxy.ansible.com/download/cisco-ucs-1.8.0.tar.gz
format_version: 1.0.0
name: ucs
namespace: cisco
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.8.0
version_url: https://galaxy.ansible.com/api/v2/collections/cisco/ucs/versions/1.8.0/
